### ISSUE TITLE
missing index.d.ts

### ISSUE THREAD

**Issue by mthomas-github** [xiqi/react-native-unordered-list#2]
Could not find a declaration file for module 'react-native-unordered-list'. 'node_modules/react-native-unordered-list/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-unordered-list` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-unordered-list';`ts(7016)

**Comment by xiqi** [comment]
@mthomas-github Thank you!
I've released a new version [v1.0.4](https://www.npmjs.com/package/react-native-unordered-list/v/1.0.4) that includes a declaration file.
